server:
  port: 1001
spring:
  application:
    name: "Company"
    profiles:
      active: "dev"


  config:
    import: "optional:configserver:http://localhost:8071/"

  datasource:
    url: jdbc:mysql://localhost:3306/companydb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    org.springframework: DEBUG
build:
  version: "1.0"

company:
  message: "Welcome to Reviews Company Service - Development Environment"
  contactDetails:
    name: "Baharul - Development Owner"
    email: "bob.johnson@eazybank.com"
  onCallSupport:
    - "(555) 555-3333"
    - "(555) 555-4444"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "company"
    description: "Niyaz Company Application"
    version: "1.0.0"