server:
  port: 1002

spring:
  application:
    name: "Jobs"
  profiles:
    active: "dev"

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/jobdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

build:
  version: "3.0"

jobs:
  message: "Welcome to Niyaz Jobs Service - Development Environment"
  contactDetails:
    name: "Niyaz Asghar - Developer"
    email: "niyazAsghar.dev"
  onCallSupport:
    - "(555) 555-1111"
    - "(555) 555-2222"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "jobs"
    description: "Niyaz Jobs Application"
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000