server:
  port: 8080

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:mysql://localhost:3306/companydb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
