server:
  port: 1001

spring:
  profiles:
    active: dev
  application:
    name: "company"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    config:
      discovery:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/companydb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "company"
    description: "Niyaz Company Application"
    version: "1.0.0"
